name: Build and Test All Lessons

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up C++ compiler and dependencies
      - name: Set up C++ compiler
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      # Step 3: Build the C++ project
      - name: Build the project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      # Step 4: Run tests
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure


