name: Build and Test All Lessons

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up C++ compiler
      - name: Set up C++ compiler
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Step 3: Compile only files with a main function
      - name: Compile C++ files with main function
        run: |
          for file in *.cpp; do
            if grep -q "int main" "$file"; then
              executable="${file%.cpp}"
              echo "Compiling $file to $executable..."
              g++ -o "$executable" "$file" || exit 1
            fi
          done

      # Step 4: Run the executables
      - name: Run the executables
        run: |
          for executable in $(ls | grep -v '\.cpp$'); do
            echo "Running $executable..."
            ./"$executable" || exit 1
          done

